services:
  mongo:
    image: mongo:6.0.9
    container_name: mongo_container_6.0.9
    ports:
      - "6000:27017"
    volumes:
      - mongo_data:/data/db
    restart: 
      always

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: music_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/music-db
    command: ["node", "build/src/server.js"]    # Runs the connection to Mongo DB separately
    restart: 
      always

  frontend:
    build:
      context: ../client/my-first-project
      dockerfile: Dockerfile
    container_name: music_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: 
      always

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"

volumes:
  mongo_data: